// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migfer_Kariyer.Data;

#nullable disable

namespace MigferKariyer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250801103736_Mig_1")]
    partial class Mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Migfer_Kariyer.Entities.FieldofSpecialization", b =>
                {
                    b.Property<int>("FieldofSpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldofSpecializationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldofSpecializationId");

                    b.ToTable("FieldofSpecializations");
                });

            modelBuilder.Entity("Migfer_Kariyer.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Migfer_Kariyer.Entities.InstructorFieldofSpecialization", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("FieldofSpecializationId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "FieldofSpecializationId");

                    b.HasIndex("FieldofSpecializationId");

                    b.ToTable("InstructorFieldofSpecializations");
                });

            modelBuilder.Entity("Migfer_Kariyer.Entities.InstructorFieldofSpecialization", b =>
                {
                    b.HasOne("Migfer_Kariyer.Entities.FieldofSpecialization", "FieldofSpecialization")
                        .WithMany("InstructorFieldofSpecializations")
                        .HasForeignKey("FieldofSpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Migfer_Kariyer.Entities.Instructor", "Instructor")
                        .WithMany("InstructorFieldofSpecializations")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldofSpecialization");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Migfer_Kariyer.Entities.FieldofSpecialization", b =>
                {
                    b.Navigation("InstructorFieldofSpecializations");
                });

            modelBuilder.Entity("Migfer_Kariyer.Entities.Instructor", b =>
                {
                    b.Navigation("InstructorFieldofSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
